LOAD DATA LOCAL INFILE './resources/synthetic/Codes.txt'
INTO TABLE T_CODES
FIELDS TERMINATED BY ','
(CODE_KEY, CODE_TYPE, CODE_DESC)
SET CODE_ID = NULL AND CREATED_ON = NULL;

LOAD DATA LOCAL INFILE './resources/synthetic/Codes.txt'
INTO TABLE T_CUSTOMER
FIELDS TERMINATED BY ','
(F_NAME, L_NAME, EMAIL, USERNAME, PASS)
SET ACCOUNT_ID = NULL AND ADMIN = NULL AND ACTIVE = NULL AND CREATED_ON = NULL AND LAST_LOGIN_DATE = NULL;

#Sets the first user, admin to an admin account
UPDATE T_CUSTOMER SET ADMIN = 1 WHERE ACCOUNT_ID = 1;

LOAD DATA LOCAL INFILE './resources/synthetic/Codes.txt'
INTO TABLE T_ACCOUNT
FIELDS TERMINATED BY ','
(ACCOUNT_ID, ACCOUNT_TYPE)
SET LAST_UPDATED = NULL AND AMOUNT = 0;
